### ISSUE TITLE
GraphSpace: Git for graphs

### ISSUE THREAD

**Issue by adbharadwaj** [nrnb/GoogleSummerOfCode#112]
### Background
[GraphSpace](http://graphspace.org) is an easy-to-use web-based platform collaborating research groups can use for storing, interacting with, and sharing networks. A GraphSpace user can upload graphs through a REST API, import graphs created in Cytoscape, interact with graphs (view them, customize layouts, and save layouts), share graphs (create groups and add collaborators, share graphs among all members of a group or with the world), search graphs, and organize graphs using tags. GraphSpace has a comprehensive REST API that allows users to communicate programmatically with it.

### Goal

The overall goal of this project is to implement a simple version of "Git for Graphs", which will allow users to track changes made to a graph, to describe these changes, as well as to easily undo these changes. This feature will help users to document the process and workflow that produced the given graph. Here is a list of features that the versioning system must support:

- **Versioning** - This is the main goal of the project. Users should be able to create and save different versions of the same graph. They should provide a "commit" message that describes the changes in the given graph with respect to previous graphs. Each version should have a unique link.

- **Backtracking** - Users should be able to go back to previous versions at any point of time using graphical interface and RESTful interface.

- **Layout compatibility** - Since there may be different versions of the same graph, a layout that was created for one version may not be compatible with a later version. In order to support layout compatibility, we propose to add a feature which will allow users to:
    - Transfer layouts from one version to another. This action is similar to creating a pull request in Github.
    - Layout compatibility check. If the layout is not compatibility, the tool should report the conflict. This check is similar to Github’s feature to check if a pull request is ready to merge or not.

### Difficulty Level
Level 2

### Skills
List skills/technologies that the student should be familiar with. 

- Python, Django, Databases (SQL), HTML, JS, CSS (essential)
- PostgreSQL, Git, Jquery, Cytoscape.js (nice to have)

### Public Repository
https://github.com/Murali-group/GraphSpace/

### Potential Mentors
[Aditya Bharadwaj](https://adbharadwaj.github.io/)
[T. M. Murali](http://bioinformatics.cs.vt.edu/~murali/)

### Contact

[adb@vt.edu](adb@vt.edu)
[murali@cs.vt.edu](murali@cs.vt.edu)

**Comment by sarthak-srivastava** [comment]
Hi, I am Sarthak and I am really interested in the project. I have done quite a few projects on web development and am fairly comfortable with Django(Python), SQL, HTML, JS ,CSS ,Jquery ,Git. I wanted to ask what level of expertise and experience is exactly expected of potential student.

**Comment by adbharadwaj** [comment]
Hi @sarthak-srivastava 

Thanks for showing interest in this project. We are currently asking all potential students to fix an issue on GraphSpace in order to showcase their familiarity with the above-mentioned technologies. This will also ensure that you already know how to contribute to an open-source project by the time GSoC actually starts. 

If you have done some project using Django, it should be enough. SQL is an essential skill for this project. We maintain a SQL database and you need to be familiar with Database concepts in order to contribute to this project. If you have taken a course in Database, you should be good to go. For HTML,JS,CSS - we mostly use bootstrap for styling our page. So, if you have use bootstrap before - it shouldn't be hard for you to contribute.

We have a list of issues labeled with good first issue to help potential first-time contributors. Incase you like to fix an issue, you can comment on the given issue and let us know.

You can also refer to the following list of instructions for Potential GSoC students to get started.

**Comment by adbharadwaj** [comment]
To all prospective applicants,

Please refer to [instructions for potential GSoC students](https://github.com/Murali-group/GraphSpace/wiki/Instructions-for-Potential-GSoC-Students) to get started.

**Comment by jahandaniyal** [comment]
Hi Mentors,

I would love to work on the **"Git for graphs"** project as a part of **2018 GSOC**. 
In order to familiarize myself with the source code of **Graphspace** I will try my hands on some of the 'good first issues'. I'm in the process of completing the local setup (currently on a windows 10 surface tablet - though I will be working mostly on Ubuntu ). I have read few sections of the **Graphspace** usage manual and I believe it should be sufficient to tackle the 'good first issues'. 
I saw a suggestion by one of the Mentors to improve the README.MD documentation. If you want, I can add a separate section listing the steps to build on Windows. Perhaps add download links of requirements as well. 

**Some details about myself** 
I'm currently pursuing Master of Computer Science at the Technical University of Berlin (TU Berlin). 
I have about 2 years of experience working as a Full-Stack Web Developer.
Technology stack of the project  - 
Django, Python, Bootstrap, JQuery, Knockout.js, PostgreSQL, jqplot (and few other graphical library).

In 2013, while pursuing Bachelor's of Technology, I made a simple Graph visualization application using Java-Swing. It creates a graphical representation of un-directed acyclic graphs (input is a datafile) and it allows the user to interactively find the shortest path between two nodes. It was a very small hobby project and in no way does it compare with Graphspace. I thought it was worth mentioning, as this is the reason why I'm so interested in this project.

**Comment by jahandaniyal** [comment]
Hi Mentors @tmmurali @adbharadwaj , 
I have gone through the instructions for Potential GSOC Students and I have been working on few issues currently. I wish to pursue this project for GOSC '18, to this end I would like the forward my Resume. 
Please let me know if it is the right time to forward my resume. 

Thanks.

**Comment by tmmurali** [comment]
Sure. Please send us your resume.

**Comment by khanspers** [comment]
GSoC 2018
