### ISSUE TITLE
Web service for SBGN <-> BioPAX conversions, and some other BioPAX related operations

### ISSUE THREAD

**Issue by ozgunbabur** [nrnb/GoogleSummerOfCode#121]
### Background

[BioPAX](http://www.biopax.org/) is a widely used pathway modeling and exchange standard language, supported by many pathway databases and used as an integration medium by [Pathway Commons](http://www.pathwaycommons.org/). [SBGN](http://sbgn.org/) language (specifically the Process Description dialect, or SBGN-PD) is a standard for pathway visualization, which has been successfully used to visualize BioPAX models by several tools including SBGNViz and ChiBE. 

Ideally, we would like to have web-based pathway editors that can generate/edit BioPAX models, and visualize them using SBGN-PD notation. This ideal is challenged by the fact that the BioPAX software stack, most specifically [Paxtools](https://biopax.github.io/Paxtools/), is implemented in Java and not easily accessible to web-based tools. To bridge between BioPAX and SBGN, we need a web service that will provide a both-ways mapping and conversion, as well as provide an interface for major BioPAX operations that Paxtools provide, including graph queries.

### Goal

Build a web-server that will:
1. Take a BioPAX level 3 model as input and provide an [SBGNML](https://github.com/sbgn/sbgn/wiki/SBGN_ML) (XML implementation of SBGN) as output, as well as an ID mapping between the models.
2. Exact reverse of the previous operation.
3. Provide a web interface for other major Paxtools functions that will execute on a given BioPAX model, such as navigating through the model structure and extracting information, or several types of graph queries.

### Difficulty Level 1
Relatively easy project for a candidate with experience in building web servers.

### Skills
Required: Javascript, Java, building Java-based web services.
Optional: BioPAX, SBGN.

### Public Repository
A new repository needs to be generated.

### Potential Mentors
Ozgun Babur
(please add your name)

### Contact
[Ozgun Babur](https://github.com/ozgunbabur)

**Comment by haleyyew** [comment]
I want to work on this project. I worked with NRNB last summer, the project was [SBML to SBGN interconversion](https://github.com/nrnb/GoogleSummerOfCode/issues/67), and my mentors were Nicolas Rodriguez and Sarah Keating. My project repository can be found [here](https://github.com/NRNB-GSoC2017-SBML2SBGNML-Converters/SBML2SBGNML)

The first 2 goals of this project seems easy, because I already have experience with SBGN-PD and I implemented a converter in Java. The converter between BioPAX and SBGN-PD should be similar. What I'm highly interested in is building a web service that also supports diagram editing and graph querying. However, by looking at SBGNViz I realize that a web service has already been build for SBGN-PD. What I'm wondering is if we can visualize BioPAX directly without converting to SBGN-PD first? For example, can I build a web tool similar to ChiBE, that supports similar operations? 

After completing the project last summer, I took a step further to explore more about SBML. I downloaded the dataset [here](https://www.ebi.ac.uk/rdf/documentation/biomodels/) and implemented a graph navigation tool as a school project. The incomplete version of project can be found [here](https://github.com/haleyyew/CPSC547_project). I used D3.js as my library for data visualization, and several simple algorithms in the backend for graph querying and data filtering. Therefore I think I'm highly qualified to work on this project.

However, I need to point out that I'm a first year M.Sc student and I might have other commitments with my supervisor this summer. Therefore I might not be able to work on this project full-time. Will this be okay?

**Comment by ozgunbabur** [comment]
Hi Haoran, your past experience seems well suited for this or a related
project, however, GSoC requires students to be full time. Please see

https://developers.google.com/open-source/gsoc/faq#how_much_time_does_gsoc_participation_take

Let us know if your commitments change.

Best,
Ozgun

**Comment by ozgunbabur** [comment]
This project is still current. Reopening.
