### ISSUE TITLE
App Store for Cytoscape

### ISSUE THREAD

**Issue by AlexanderPico** [nrnb/GoogleSummerOfCode#122]
### Background
The [Cytoscape App Store](http://apps.cytoscape.org/) is an interactive website for browsing, submitting and installing Cytoscape apps. [Cytoscape](http://cytoscape.org) is a free, open source  data visualization tool for biomedical research, focused on molecular networks. There are over 330 apps in the App Store that bring specialized functionality to Cytoscape, including database access, data-driven visualization and novel analysis capabilities. The site sees over 1000 downloads per day from users of the Cytoscape research tool. The Cytoscape App Store has been running successfully for a few years, but the list of requests for new features has been accumulating. A motivated student with an interest in advanced web development could make major enhancements to the site.

### Goal
We have a list of features to implement for the site, ranging from entry-level to advanced. Per your interests and skill, propose to us which of these features you think you could complete in the time you have. Additional features can be suggested as well.

- Highlight and incentivize adding profile information to app pages
- Improvements to app search
- Expand capabilities to inspect submitted apps (e.g., pom.xml) and extract structured information for icons and categorization, e.g., does the app add a layout to Cytoscape's menu?
- Implement a new _Web App Builder_: a simple form where folks could register URLs and Titles that can either be added to a list of community bookmarks in [CyBrowser](http://www.cgl.ucsf.edu/cytoscape/utilities3/cybrowser.shtml) or as independent apps that folks could install to access 3rd party sites.
- Implement a web app for viewing the App Store from within [CyBrowser](http://www.cgl.ucsf.edu/cytoscape/utilities3/cybrowser.shtml). This could be an app manager replacement.
- Support user reviews and comments from within Cytoscape (i.e., when they are using the app). Optionally send these to the registered app authors.
- Add support for submitting, browsing, downloading R and Python scripts.

### Difficulty Level 1
Technically, this is an easy project. However, advanced user-centric design skills, UI/UX skills and deployment skills will be needed. 

### Skills
Django, Python, JavaScript (essential)

### Public Repository
GitHub repo: [cytoscape/appstore](https://github.com/cytoscape/appstore)
Issue tracker: [cytoscape/appstore/issues](https://github.com/cytoscape/appstore/issues)

### Potential Mentors
- [Alex Pico](alex.pico@gladstone.ucsf.edu)
- Chris Churas
- Yihang Xin
- Scooter Morris

**Comment by vnyk** [comment]
Hi I want to work on it.

**Comment by AlexanderPico** [comment]
Hi vnyk. Thanks for your interest. The GSoC program is driven by self-motivated students. Can you browse the code, brainstorm on solutions and ideas, and then introduce yourself, including more about your background, skills and interests?

**Comment by souravsingh** [comment]
Hello, I am interested in the project.

I am currently a final year undergraduate student and a certified software carpentry instructor and I am interested in the field of Phylogenetics, Proteomics, High-Throughput sequencing and Machine Learning. I have a working knowledge of Django and Javascript.

About some of the ideas for the project, the uploading part can be done simply by adding a ``FileField`` in forms and putting the views for uploads.

For reviews, I suggest using ``django-reviews`` package for putting reviews.

And for icons, I suggest storing them as static files and linking them in the corresponding HTML files.

These are some thoughts I have in my mind.

**Comment by AlexanderPico** [comment]
I'm getting some great questions and suggestions for this project! (thanks @souravsingh and Maria) I'll try to answer them here and share updates with all potential applicants.

1. `django-reviews` package for adding review support. Can you describe how user identification is handled by this package? For example, we would like to support anonymous reviews, rating and issue report, but at the same time provide an option for specifying email if they want to be contacted. We do not want to require login accounts for users of the app store since these accounts are not currently required for typical usage (except app submission and page editing). Also, what kind of API is provided for reviews? Can we support issuing reviews from the Cytoscape Java application (i.e., where the user is actually using the app) and then send and collect the reviews on the app store page?

2. Using `FileField` to support file upload is the easy part. What we'll need to see in good proposal will be a design for how uploaded scripts would be presented, i.e., in a way that is distinct from apps and clear about how they might be used. This requires taking sometime to understand how apps and scripts work in the Cytoscape ecosystem.

3. The goals are not in any particular order. It's up to you to propose which of these you can complete during the program, how you would implement them, and how the final product would function/look. If you have more in depth questions about particular issues, just ask.

4. You are at liberty to propose icons, UI/UX and implementation plans. In fact, that is precisely what we expect in your applications. The more details and independent ideas your propose the better we can assess your level of interest and capabilities.

5. The CyBrowser related ideas are probably the most intricate (in terms of concept), but not necessarily the most difficult (in terms of implementation). Take some time to read the linked resources about CyBrowser. Realize that it is essentially a browser _in Cytoscape_, which supports HTML and JS, like most any browser. In addition, CyBrowser supports a special protocol type `cycmd` that allows you to trigger [Cytoscape Commands](http://manual.cytoscape.org/en/stable/Command_Tool.html). Putting it all together, you can design simple web pages that have links and buttons that control Cytoscape when viewed in CyBrowser!

Keep the questions coming!

**Comment by souravsingh** [comment]
'django-reviews' handles user identification through their account info. In case, the user is anonymous, there is a setting called `REVIEWS_IS_NAME_REQUIRED` and `REVIEWS_IS_EMAIL_REQUIRED` for storing their names and e-mail for future contact. 

As for `FileField`, I propose displaying the scripts as a Notebook(if they are Python scripts) or as color-highlighted code once the upload is done.

**Comment by soccerdroid** [comment]
Hello again!
I'm Maria. I have a couple of questions in order to make my proposal. I am planning to implement the first, second and sixth features listed in the project idea. In your repo I saw the App model, which has attributes like tags. Are the tags the ones you use to generate the icons? What can a tag tell me about an app? How do you categorize the apps? When you mention to extract structured information, what attributes of the App model can give me that information? I don't have clear that part. I also checked the cytoscape-automation repo, because I wanted to see if it exists a method for knowing when cytoscape is running, but I could not find it. Does such method exist? If not, how can I detect if Cytoscape is opened with Javascript? In order to be able to implement the sixth feature mentioned, which is about support user reviews and comments from within Cytoscape. Thanks in advanced for your help

**Comment by AlexanderPico** [comment]
Hi @soccerdroid (Maria),

In the App model, tags correspond to the categories that app authors can manually assign (or "tag") their apps with. These categories are listed on the left side of the main page for the app store and as "Categories:" on each app page. The icons are currently associated with specific model attributes for each case, such as competition_winner_dec_2012, which leads to the trophy icon.

Currently, tags (categories) and icons are manually added by authors and editors. The part about "extracting structured information" is really just about identifying useful information from structured sources (like the pom.xml) provided by app authors already and using that to automatically set certain tags and icons to help reduce the manual labor.

Cytoscape opens a dedicate port for the App Manager when it's running, so this is the simplest way to check that by js: https://github.com/cytoscape/appstore/blob/master/static/apps/js/app_page.js#L10 

Thanks for the questions!

**Comment by soccerdroid** [comment]
Oh ok. I checked about what automation means for cytoscape apps, could you consider an app as automated if it submits an api? I say this because here https://docs.google.com/document/d/1QTrT-9ylhI4OX5DkauMo2ujLIqeg3WDUDwl77KLtfVY/edit it says that automation functionalities are built with CyREST. I think a tag of automation or CyREST use in the pom.xml file could be used to detect automated apps.

**Comment by AlexanderPico** [comment]
@soccerdroid Yes, precisely.

**Comment by soccerdroid** [comment]
Hello, I have somo troubles with the dependencies installation for running the repo in my computer. I cannot install PIL, because it is now donwloaded its fork Pillow. I also have troubles with xaniap installation and the libpng library. I want to see the templates after someone submits an app, this is, to see the form where you edit the app and add a description, tags, etc. I have already made a prototype, but I would like to attach it to the existing template in order to be consistent.

**Comment by soccerdroid** [comment]
I have Ubuntu 16.04

**Comment by matthiaskoenig** [comment]
Hi @soccerdroid,

I got this project working in a local virtualenv.
See the changes in the following pull request.
https://github.com/cytoscape/appstore/pull/32

I documented the requirements in `requirements.txt` and the necessary installation instructions to run this locally in `INSTALL.md`

https://github.com/cytoscape/appstore/pull/32/commits/065f130a2daad11d53738b7776d857575a299fca

Main issue for me is that the problem is only `python 2` and relies on a very old django version `django < 1.9`. This has many security issues. Probably a good idea to update the codebase to `python 3` and `django>2.0`.

Important thing is to force the old requirements to get this working and install xapian (I added an install script for that).

Here some proof that it runs locally:
![screenshot from 2018-03-26 12-02-56](https://user-images.githubusercontent.com/900538/37900189-cc1b0f92-30ed-11e8-85ca-65cb3765cfd1.png)

Hope this helps. Best M

**Comment by khanspers** [comment]
GSoC 2018

**Comment by somesh1234567** [comment]
hi,I am interested in this project.

**Comment by theweblover007** [comment]
Hello, I'm Pradyumna from BITS Pilani. I would love to work on this project but I notice that some of the ideas mentioned in this post must have already implemented by Sarthak Shrivastava in last year's GSoC (As i could see in his proposal document). 

The issues that i am talking about are :
1.Implement a web app for viewing the App Store from within CyBrowser. This could be an app manager 
   replacement.
2.Support user reviews and comments from within Cytoscape (i.e., when they are using the app). 
   Optionally send these to the registered app authors.
3.Add support for submitting, browsing, downloading R and Python scripts.

Please clarify whether these ideas need to worked upon or not.

**Comment by AlexanderPico** [comment]
These aims are still active. They are sort of a laundry list of possible features and we don't expect to complete them all in a summer.

The primary goal will be to streamline the deployment through to production.

**Comment by ksvkabra** [comment]
Hello @AlexanderPico , I am Keshav Kabra from JECRC, Jaipur. I am interested in working on this project

**Comment by AlexanderPico** [comment]
@ksvkabra Great. Explore the links provided in the project description, review the materials at https://nrnb.org/gsoc.html, then start a Google Doc with your proposal. Mentors will provide feedback on your proposal prior to the submission date if there is time.

**Comment by khanspers** [comment]
Active GSoC 2019 project.

**Comment by AlexanderPico** [comment]
Editing and reopening for 2021

**Comment by spursbyte** [comment]
I  want to work on this issue. Can you please give more info on this?

**Comment by AlexanderPico** [comment]
The description above includes links. Research as deeply as you can and then ask questions that are as specific as possible. The way you approach problems and new learning is part of the evaluation process.

**Comment by karthikshetty03** [comment]
Hello mentors @AlexanderPico, @scootermorris, @yihangx, @coleslaw481 
I am Karthik Shetty from BITS Pilani. My primary skills are Web development (HTML, CSS, Javascript, ReactJS) and Python programming. I would like to work on this issue for GSOC 2021 and want to know more about it. 
I have gone through the Wiki of the Cystoscape Appstore's GitHub repo.
Can you please guide me on how to proceed further?

**Comment by khanspers** [comment]
Cleanup in preparation for GSoC 2022.
