### ISSUE TITLE
Expand ModelBricks.org to add user-run simulations

### ISSUE THREAD

**Issue by vcellmike** [nrnb/GoogleSummerOfCode#154]
### Background
VCell (http://vcell.org) is an open source software platform that can model and simulate reaction-diffusion systems in geometries derived from 3D experimental microscopy images; it can also utilize experimentally derived molecular concentrations and cellular localizations. It is used by scientists around the world to create quantitative hypotheses of cellular functions whose predictions can be directly compared to experimental results. http://ModelBricks.org project is an effort focused on describing recurring patterns in biological networks that correspond to such biological concepts as metabolic reaction, catalysis, inhibition, protein phosphorylation, complex formation, transcription, translation etc. These patterns are described as small VCell models (ModelBricks) that are retrieved from VCell database and displayed online at http://modelbricks.org website (currently deployed at https://model-bricks-testing.herokuapp.com/).

### Goals
Expand ModelBricks website into the portal for all VCell models using existing VCell API
a. Implement user logging in and viewing his/her private models.
b.Enable convenient display of simulation results.
c. Enhance API to enable search by model elements (species, URI)
d. Enhance API to enable model permissions change
e. Enhance API to enable running/stopping simulations and see progress.

### Size and Length of Project
-**175 hours**
-12 weeks

### Skills
HTML, CSS, JavaScript, Java (essential)
NodeJS  (desirable)

### Public Repository
ModelBricks:
https://github.com/noahlb123/ModelBricks_source/tree/Internship
VCell API:
https://github.com/virtualcell/vcell/tree/master/vcell-api/src/main/java/org/vcell/rest/server

### Potential Mentors
Michael Blinov
Frank Morgan
Ann Cowan

### Contact
[Michael Blinov](mailto:blinov@uchc.edu)
Frank Morgan
Ann Cowan

**Comment by sraghuvanshi** [comment]
Hi @vcellmike !
Greetings of the day

This is Saksham Raghuvanshi, interested in doing summer internship (GSOC) in NRNB.
I’m a Computer science undergrad student from India, currently in 2nd year. I’m passionate about web development and web design but more importantly, I carry a goal to make this world a better and more sustainable place.

"VCell API for ModelBricks.org", This project seems very exciting to me.  Also, It is great to know that you are focusing on user experience because I believe that “to the users, the interface is the product”. I would love to contribute to this project.

### My Skills 
**Programming** : HTML, Javascript (ES6), C, Java
**Libraries and Framework** : Node.js, Vue.js, JQuery, Express, Handlebars, typescript
**Design** : CSS, SASS, Photoshop, illustrator, shotcut 
  
https://github.com/modelbricks/modelbricks.github.io 
I've cloned this repository but I'm not able to run it locally. Maybe I'm not using the right commands required to execute this project. It would be very helpful if you could guide me with the setup. 

Looking forward to hearing from you,

Thanks a lot,
Saksham Raghuvanshi

**Comment by vcellmike** [comment]
Hi Saksham,

There is nothing to run at https://github.com/modelbricks/modelbricks.github.io, these are github pages that after cloning you can either setup as your own github pages (https://dev.to/programliftoff/create-your-first-website-on-github-pages), or copy into a local directory and test in a browser. Check test.html for the latest version that has JavaScript and CSS. The first part of the project is just that - updating all pages at modelbricks.org website with Javascripts as in test.html
The second part is also HTML, but Java-generated. Look at https://github.com/virtualcell/vcell/blob/master/vcell-api/src/main/java/org/vcell/rest/server/BiomodelVCMLModelInfoResource.java - these is HTML formatted from VCell API. You'll need to decompose this file into several that generate pieces of HTML and insert them into model pages, e.g. https://github.com/modelbricks/modelbricks.github.io/edit/master/pages/CM_PM12648679_MB10.md (check for vcellapi). Hope it helps.

**Comment by sraghuvanshi** [comment]
Thank you, sir, for explaining the project.  :smiley: 
I'm very excited to work on it. I have prior experience with VCell API, so that makes the project even more suitable for me. 
Sir, I wanted to know, do I have the freedom to redesign the website with completely new and modern user interface? I propose that we develop it using Vue.js (Front-end framework), as there are many advantages of using Vue.js like: 
- It's a powerful tool for developing complex and interactive user interfaces.
- Maintainable, modular, standalone architecture
- Makes it easy for other developers to contribute
- Easy to update the website in the future

Also, sir let me know if there is any front-end related issue that I can work on. 
Thanks again!

**Comment by khanspers** [comment]
Active project for GSoC 2020, closing here.

**Comment by khanspers** [comment]
This is an active GSoC 2021 project. The issue will be closed for the duration of GSoC since it is no longer available to other students.

**Comment by khanspers** [comment]
NRNB has officially been accepted as a mentoring organization for GSoC 2022! Here are some useful links:

- [Project proposal template](https://docs.google.com/document/d/1Zi6L38CHEeq2aL6xzv0Ozhd_Y6D71W3yCBGHplmxr6k/edit?usp=sharing)
- [GSoC contributor guide](https://google.github.io/gsocguides/student/)
- [Program timeline](https://developers.google.com/open-source/gsoc/timeline)

**Comment by osamaahmed17** [comment]
@khanspers, is this still an open project for GSOC 2022?

**Comment by vcellmike** [comment]
Yes, the description was updated to leave only issues that are still unfinished.

**Comment by khanspers** [comment]
A reminder that the application period opens on Monday April 4. Proposals to NRNB must be submitted on the official GSoC Site (https://summerofcode.withgoogle.com/) before April 19, 18:00 UTC to be considered, and contributors are encouraged to submit proposals in draft format early, so that mentors can give feedback directly at the GSoC site.

**Comment by AlexanderPico** [comment]
**IMPORTANT REMINDER: GSoC 2022 is for new “beginners” to open source.** 

Applicants are expected to review eligibility requirements prior to applying.  We can not accept applications from contributors with prior open source development experience. From the GSoC FAQ https://developers.google.com/open-source/gsoc/faq:

> Can someone already participating in open source be a GSoC Contributor?
>
> The goal of GSoC is to bring new contributors into open source organizations. GSoC can also help beginner contributors learn the ins and outs of open source while being mentored by experienced community members.
> GSoC is for new and beginner contributors to open source, it is not for experienced contributors to open source.

**Comment by khanspers** [comment]
Closing in preparation for GSoC 2023.
