### ISSUE TITLE
Develop a Standalone CellDesigner to BioPAX Converter

### ISSUE THREAD

**Issue by cannin** [nrnb/GoogleSummerOfCode#177]
### Background
CellDesigner (http://www.celldesigner.org/) is a tool for drawing and modeling biological networks. CellDesigner has a plugin (https://academic.oup.com/bioinformatics/article/27/24/3437/306597) to export networks in the BioPAX (biopax.org), a format that ignores much of the visualize styles of CellDesigner to retain just the "biological content". 

### Goal
The goal is to reproduce the BioPAX export plugin as a standalone tool. The Supplementary Data file from (https://academic.oup.com/bioinformatics/article/27/24/3437/306597) provides information about the mapping that needs to occur. Ideally, the project would either use Java BioPAX library (https://github.com/BioPAX/paxtools) or call it from Python using Pyjnius (https://pyjnius.readthedocs.io/) when necessary (e.g., to validate output).

### Difficulty Level 2
This project will require users to become quickly familiar with two XML-based formats. 

### Skills
* Essential skills: Java (or Python), XML

### Public Repository
* There is currently no code repository for this project 
* https://github.com/BioPAX/paxtools
* Getting started with Paxtools: https://github.com/cannin/biopaxTutorial
* Example Groovy (Java-based) code for using Paxtools: https://gist.github.com/cannin/b6f7ba64e1156b001282

### Potential Mentors
[Augustin Luna](mailto:aluna@jimmy.harvard.edu)

**Comment by ballaneypranav** [comment]
Hi, I'm Pranav Ballaney from India, and I would like to work on this project for GSoC 2021. I'm a Biology and Computer Science major, and I worked as part of GSoC last year with Debian on quality assurance and continuous integration of bioinformatics applications. 

I've gone through the publications and resources posted here, and I've built a basic prototype for the converter [here](https://github.com/ballaneypranav/celldesigner-biopax). The file I've used as input is a sample that comes with the CellDesigner installation. The converter is rudimentary and works only with this simple model. The output passes the [BioPAX Validator](http://biopax.baderlab.org/) with no errors, but some warnings are shown. 

I have used a procedural approach here since it's just a prototype, but I would like to develop the software further with a more modular and object-oriented approach. 

Please take a look at [the prototype](https://github.com/ballaneypranav/celldesigner-biopax) and let me know what you think.

Regards,
Pranav

**Comment by ballaneypranav** [comment]
Hi, I just wanted to ask whether you had a chance to take a look yet. If you would like me to continue working on it, please let me know.

**Comment by cannin** [comment]
@ballaneypranav sincere apologies for the delay. I earlier did look at the code; it is an amazing start. Part of the delay has been an ongoing discussion with a potential co-mentor regarding "converter" projects: https://github.com/nrnb/GoogleSummerOfCode/issues/175 and https://github.com/nrnb/GoogleSummerOfCode/issues/177 and we still have to settle a clear direction. A meeting to settle some points is expected tomorrow.

**Comment by ballaneypranav** [comment]
Thanks a lot, @cannin! Have any changes been made to this project? If you would like me to continue developing this some more as an evaluation task, please let me know; otherwise, I can directly submit a proposal.

**Comment by cannin** [comment]
I'm closing this project in favor of #175 @ballaneypranav please see that project in case you are still interested
