### ISSUE TITLE
Implement an SBML simulator in pure Rust

### ISSUE THREAD

**Issue by funasoul** [nrnb/GoogleSummerOfCode#190]
### Background
The programming language Rust has been used in various fields for its robust memory management while boasting execution speed comparable to the C/C++ language. It is now being applied to the development of bioinformatics tools.
In the future, these tools will be increasingly used via the Web, and implementation in the Rust language is expected to ensure the safety of these tools. Against this background, we would like to confirm its effectiveness in the simulator development area.

Last year, as a part of a [GSoC project](https://summerofcode.withgoogle.com/archive/2021/projects/4702026784571392), an SBML simulator was developed using Rust ([sbml-sim](https://github.com/libsbmlsim/sbml-sim)). To support SBML and MathML parsing, two other tools ([mathml-rs](https://github.com/libsbmlsim/mathml-rs) and [sbml-rs](https://github.com/libsbmlsim/sbml-rs)) were also developed. The [SBML test suite](https://sbml.org/software/sbml-test-suite/) was used to verify working and compare performance with existing simulators. A detailed description of the implementation is available in the [final report](https://docs.google.com/document/d/1f2xqqWRrk_Dzi5WFWem20CN49SxDtxttoQcZzBCzHck/edit?usp=sharing). 

### Goal
The goal this time is to extend the implementation from last year. Good starting points are failing test cases. We would aim to support more SBML features, such as ConversionFactors, CSymbols and Events without delays. 

### Project Details
**Size:** 175 hours (medium)
**Length:** 12 weeks
**Difficulty:** Medium

### Skills
Essential: Rust
Preferred: numerical simulation algorithms, tree data structure, Rust procedural macros

### Resources
**Rust:** 
1. [Let's Get Rusty on YouTube](https://www.youtube.com/c/LetsGetRusty)
2. [The Rust Programming Language book](https://doc.rust-lang.org/book/)
3. [Jon Gjengset's YouTube channel](https://www.youtube.com/c/JonGjengset)
4. [Ryan Levick's YouTube channel](https://www.youtube.com/c/RyanLevicksVideos)

**SBML:** This is an XML format that describes biological systems, with chemical species, reactions, rate laws, etc. First, learn about XML, then refer to the [SBML L3V2 specification](https://sbml.org/documents/specifications/).

### Application Task
Write a Rust program to parse the SBML model in section 7.2 of the [SBML L3V2 specification](http://co.mbine.org/specifications/sbml.level-3.version-2.core.release-2.pdf). Print each species and compartment along with its value in default model units. Also print values in units associated to each species/compartment if a corresponding `conversionFactor` is defined. No need to deal with any other SBML components for this task.

### Public Repository
- [SBML](http://sbml.org)
- [libSBMLSim](https://github.com/libsbmlsim/)
- [sbml-sim (in Rust)](https://github.com/libsbmlsim/sbml-sim)

### Potential Mentors
[Akito Tabira](https://github.com/mythosil/)
[Akira Funahashi](https://github.com/funasoul/)
[Kaito Ii](https://github.com/kaitoii11)
[Takahiro Yamada](https://github.com/TakahiroYamada)
[Yuta Tokuoka](https://github.com/tokkuman)
[Pranav Ballaney](https://github.com/ballaneypranav)

### Contact
[Akito Tabira](mailto:mythosil2008@gmail.com)
[Akira Funahashi](mailto:funasoul@gmail.com)
[Kaito Ii](mailto:kaitoii1111@gmail.com)
[Takahiro Yamada](mailto:yamataka.genetics@gmail.com)
[Yuta Tokuoka](mailto:bowbrand1227@gmail.com)
[Pranav Ballaney](mailto:ballaneypranav@gmail.com)

**Comment by EMUL8ER** [comment]
Hi I am shashwat,I would like to contribute to this project,could u please point me to the resources to get started.

**Comment by TakahiroYamada** [comment]
Hi @EMUL8ER

I'm Takahiro, one of the potential mentor of this project.

Could you please introduce yourself first?
If you can tell us about your programming experience, your activities in the Open Source Community, and whether or not you have participated in GSoC before and etc, it will help us to facilitate and provide you with important reference material for this project.

Best.

Takahiro

**Comment by EMUL8ER** [comment]
Hi @TakahiroYamada I have experience with C++,Python, and data structures and algorithms and also built curriculum projects in Machine Learning, I will learn rust as required, I am fairly new to the open source communtiy and never participated in gsoc, and wish to be part of it.
Thank you :)

**Comment by TakahiroYamada** [comment]
Thanks for immediate response, @EMUL8ER .

OK. Since knowledge of Rust is essential to proceed this project, I think it is first necessary for you to understand Rust by referring to the contents of the following URLs and others.
https://doc.rust-lang.org/book/title-page.html

If you have any other good reference information about Rust, could you please add it? >> @ballaneypranav 

As for numerical integration, I suppose it is better for you to understand the method first by referring to the following URL (Euler method is the easiest and most basic method, so I think the best way to do this is to understand the theory behind it).

http://faculty.olin.edu/bstorey/Notes/DiffEq.pdf

@EMUL8ER , do you have any experience with SBML?

Takahiro

**Comment by EMUL8ER** [comment]
@TakahiroYamada  I took a university course on Numerical methods(euler,newton raphson, runge kutta, simpsons rule etc) but have no prior experience related to SBML, but I am willing to learn and invest time in this project.
Thank you

**Comment by ballaneypranav** [comment]
Hi @EMUL8ER, thanks for your interest in this project. Here are some resources I found helpful last year.

**Rust:** 
1. [Let's Get Rusty on YouTube](https://www.youtube.com/c/LetsGetRusty): Beginner videos here should be sufficient for starting out, check out the other two later if interested.
2. [The Rust Programming Language book](https://doc.rust-lang.org/book/): The book is an excellent resource, as @TakahiroYamada pointed out.
3. [Jon Gjengset's YouTube channel](https://www.youtube.com/c/JonGjengset)
4. [Ryan Levick's YouTube channel](https://www.youtube.com/c/RyanLevicksVideos)

**SBML:** This is an XML format that describes biological systems, with chemical species, reactions, rate laws, etc. First, learn about XML if not already familiar, then refer to the [SBML L3V2 specification](https://sbml.org/documents/specifications/).

**Comment by EMUL8ER** [comment]
@ballaneypranav  Thanks for the resources :)

**Comment by TakahiroYamada** [comment]
Thanks @ballaneypranav !
Yes, Understanding the SBML specification is also very important for this project!
Please study this as well so that your simulator can be made to comply with this specification exactly. >> @EMUL8ER 

And, I understand you have the basic knowledge about theory and direction of numerical integration.
As you know, various methods have been proposed for numerical integration to enable accurate calculations depending on the differential equation of interest.
As for which methods you should understand, including the theory, it would be good if you study the methods implemented in libSBMLsim (https://github.com/libsbmlsim/libsbmlsim), since many of them are useful (but studying Rust and the SBML specification is more important than these).

In order to start a project at GSoC, the first step is to put together an Application for this project, submit it to Google, and have it approved (Timeline is in https://developers.google.com/open-source/gsoc/timeline ).

Before putting together an application, it would be better if you can add some code to the current code, after studying Rust, numerical integration, and SBML specifications as mentioned so far.

Can you please prepare some point to add about the Rust simulator? >> @ballaneypranav 

Once @EMUL8ER distinguishes that you completed your study of these contents sufficiently, please contact us again. We can then discuss which of the things @ballaneypranav has outlined for us to do you might be able to do before submitting the application, and it would be great if you could actually make a few additions to the code and do some testing.

If you have any comments on this process, I would be happy to hear from you and other potential mentors.

Best.

Takahiro

**Comment by EMUL8ER** [comment]
Thanks @TakahiroYamada @ballaneypranav,I have started learning these and will try my best to contribute to this codebase.
Thanks :)
Shashwat

**Comment by ballaneypranav** [comment]
Sure, I'll try to create an application task over the weekend.

**Comment by khanspers** [comment]
NRNB has officially been accepted as a mentoring organization for GSoC 2022! Here are some useful links:

- [Project proposal template](https://docs.google.com/document/d/1Zi6L38CHEeq2aL6xzv0Ozhd_Y6D71W3yCBGHplmxr6k/edit?usp=sharing)
- [GSoC contributor guide](https://google.github.io/gsocguides/student/)
- [Program timeline](https://developers.google.com/open-source/gsoc/timeline)

**Comment by khanspers** [comment]
A reminder that the application period opens on Monday April 4. Proposals to NRNB must be submitted on the official GSoC Site (https://summerofcode.withgoogle.com/) before April 19, 18:00 UTC to be considered, and contributors are encouraged to submit proposals in draft format early, so that mentors can give feedback directly at the GSoC site.

**Comment by AlexanderPico** [comment]
**IMPORTANT REMINDER: GSoC 2022 is for new “beginners” to open source.** 

Applicants are expected to review eligibility requirements prior to applying.  We can not accept applications from contributors with prior open source development experience. From the GSoC FAQ https://developers.google.com/open-source/gsoc/faq:

> Can someone already participating in open source be a GSoC Contributor?
>
> The goal of GSoC is to bring new contributors into open source organizations. GSoC can also help beginner contributors learn the ins and outs of open source while being mentored by experienced community members.
> GSoC is for new and beginner contributors to open source, it is not for experienced contributors to open source.

**Comment by khanspers** [comment]
Closing in preparation for GSoC 2023.
