### ISSUE TITLE
Add new community detection/clustering algorithms to clusterMaker2

### ISSUE THREAD

**Issue by scootermorris** [nrnb/GoogleSummerOfCode#202]
### Background
clusterMaker2 is a Cytoscape app that provides a wide variety of clustering, dimensionality reduction, and ranking tools for Cytoscape users.  It integrates into Cytoscape by using Cytoscape networks and tables for the source data and updating tables, as appropriate, with results.

### Goal
New community detection/dimensionality reduction tools are being developed all the time.  There are many opportunities to expand the suite of clustering algorithms in Cytoscape.  The goal of this project is to investigate the most promising algorithms and integrate them into clusterMaker2.

### Difficulty Level: Medium/Hard
The difficulty level depends on the approach taken:
The project could be a relatively simple integration effort where an existing algorithm is implemented on the clusterMaker2 server and the app is modified to provide that implementation with the necessary data and parameters.  Alternatively, a more difficult effort might entail implementing entirely new types of algorithms into clusterMaker2, which could involve implementing new data exchange approaches, visualizations, and implementations in the app.

### Size and Length of Project
**175 hours** or **350 hours**, depending on the proposal. 

### Skills
Some Java would be useful, but if the algorithm is implemented in the back-end, any language may be used for the algorithm itself.  The back-end is on a Linux server and the middleware layer is python.

Essential skills: Some Java and possibly Python, Linux, basic familiarity with Cytoscape's data model. 

### Public Repository
https://github.com/RBVI/clusterMaker2

### Potential Mentors
Scooter Morris

**Comment by veb7vmehra** [comment]
Hey there @scootermorris I was going through the project details and I found it pretty interesting, the whole Cytoscape 3 app. As per my understanding the project is regarding first of all going over all the new clustering algorithms and examine which ones are actually efficient and should be included. The second part of the project will be to implement those algorithms at your level and final one will be put it into the cytoscape pipeline. 
I am pretty proficient with python and as I have been working in the field of Machine Learning I understand the Clustering Algorithms really well. I also have worked on Java so that won't be an issue. Again, have enough experience of working over Linux, both at personal and server level.  Finally I have Computational Biology as my Minor, thus have worked on lots of biological and genetic data which probably can help me here. Also I am efficient with many bioinformatics software.
As you probably can see that I am really interested in working over this project and would be grateful if you can discuss about this with me in detail. Thank You.

**Comment by khanspers** [comment]
A reminder that the application period opens on Monday April 4. Proposals to NRNB must be submitted on the official GSoC Site (https://summerofcode.withgoogle.com/) before April 19, 18:00 UTC to be considered, and contributors are encouraged to submit proposals in draft format early, so that mentors can give feedback directly at the GSoC site.

**Comment by khanspers** [comment]
Closing in preparation for GSoC 2023.
