### ISSUE TITLE
Improve the visualization capabilities in clusterMaker2

### ISSUE THREAD

**Issue by scootermorris** [nrnb/GoogleSummerOfCode#203]
### Background
clusterMaker2 is a top-ten app for cytoscape that provides numerous clustering, dimensionality reduction, and visualization tools for Cytoscape networks and tables.  Currently, the dimensionality reduction visualizations are implemented in Java Swing using a simple Java 2D interface.  That interface should either be significantly improved, better integrated with CyPlot or another existing plotting tool, or replaced with a JavaFX or purpose-built Javascript interface.

### Goal
Improve and extend the plotting capabilities of clusterMaker2

### Difficulty Level: Medium/Hard
Difficulty level depends on the approach taken. 

### Size and Length of Project
**175 hours** or **350 hours** depending on approach taken.

### Skills
Essential skills: Java, Cytoscape
Depending on the approach: Javascript

### Public Repository
https://github.com/RBVI/clusterMaker2

### Potential Mentors
Scooter Morris

**Comment by Sakshamgupta90** [comment]
Hi @scootermorris,
I am Saksham Gupta, a second-year B.Tech student at Maharaja Agrasen Institute of Technology, Delhi. I am proficient in Java, JavaScript, and Frontend Development. I have no knowledge about Cytoscape but it would be an opportunity for me to know for the same and it would be fun. So I would like to contribute to this project, could you please point me to the resources to get started.

**Comment by SandyW888** [comment]
Hi @scootermorris, 
Hello, I'm a senior undergraduate student major in Biochemistry and Computer Science in DePauw University. I'm familiar with bioinformatics and have taken the related class. I have used Cytoscape during the Bioinformatic class for gene clustering. I also have experience with python programming and Linux. I'm interested in your program since it's closely related to my research interest and I would love to learn more about this project.

**Comment by khanspers** [comment]
A reminder that the application period opens on Monday April 4. Proposals to NRNB must be submitted on the official GSoC Site (https://summerofcode.withgoogle.com/) before April 19, 18:00 UTC to be considered, and contributors are encouraged to submit proposals in draft format early, so that mentors can give feedback directly at the GSoC site.

**Comment by khanspers** [comment]
Closing in preparation for GSoC 2023.
